/**
 * Offline shell for the web build, generated by scripts/build-service-worker.mjs with this build's file
 * list baked in. The native app never registers it: Android ships updates through capgo, and a second
 * cache layer inside the WebView would keep serving the pre-OTA files. Nothing here calls skipWaiting —
 * a new build installs quietly and takes over the next time the game is launched, which is the same
 * promise the Android updater makes: an update never reloads a battle in progress.
 */
const CACHE = 'windward-0.2.0-ota6-34d6846a159f';
const ASSETS = [
  "./assets/ArenaScene-DY4TWhhO.js",
  "./assets/index-B-1-3eQk.js",
  "./assets/index-BpjYL1AL.js",
  "./assets/index-BthoDtVe.js",
  "./assets/index-BvjTP97m.css",
  "./assets/phaser-B8p8Giq7.js",
  "./assets/phaser-DFK5Ua9d.js",
  "./assets/web-B6Xe0daz.js",
  "./assets/web-BhWBuEIZ.js",
  "./assets/web-Cd3ukUOf.js",
  "./assets/web-DjNQL8kc.js",
  "./favicon.svg",
  "./icons/windward-180.png",
  "./icons/windward-192.png",
  "./icons/windward-512.png",
  "./icons/windward-64.png",
  "./index.html",
  "./manifest.webmanifest",
  "./portraits/assassin.png",
  "./portraits/druid.png",
  "./portraits/mage.png",
  "./portraits/ranger.png",
  "./portraits/summoner.png",
  "./portraits/warrior.png"
];

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)));
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith('windward-') && name !== CACHE).map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  // The game is a single page with no routing, so every navigation resolves to the cached shell.
  event.respondWith(request.mode === 'navigate' ? serve('./index.html', request) : serve(request, request));
});

/** Content-hashed assets never change under the same name, so the cache always wins when it has a copy. */
async function serve(key, request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(key);
  if (cached) return cached;
  try {
    return await fetch(request);
  } catch {
    return new Response('离线状态下无法获取该资源', { status: 504, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}
